[package]
name = "project-takoyaki-keygen"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
aes-gcm = "0.10.3"
anyhow = "1.0.91"
crystals-dilithium = "1.0.0"
log = "0.4.22"
pretty_env_logger = "0.5.0"
